src/Entity/Showw.php
<?php

namespace App\Entity;

use App\Repository\ShowwRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ShowwRepository::class)]
class Showw
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 60)]
    private ?string $slug = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column]
    private ?bool $bookable = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $poster_url = null;

    #[ORM\Column(nullable: true)]
    private ?float $price = null;

    #[ORM\OneToMany(targetEntity: Reviews::class, mappedBy: 'showw')]
    private Collection $reviews;

    #[ORM\ManyToOne(inversedBy: 'shows')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\ManyToOne(inversedBy: 'bookable')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Location $location = null;

    #[ORM\OneToMany(targetEntity: Representation::class, mappedBy: 'the_show', orphanRemoval: true)]
    private Collection $representations;

    #[ORM\ManyToMany(targetEntity: ArtistType::class)]
    private Collection $troupe;

    public function __construct()
    {
        $this->reviews = new ArrayCollection();
        $this->representations = new ArrayCollection();
        $this->troupe = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function isBookable(): ?bool
    {
        return $this->bookable;
    }

    public function setBookable(bool $bookable): static
    {
        $this->bookable = $bookable;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPosterUrl(): ?string
    {
        return $this->poster_url;
    }

    public function setPosterUrl(?string $poster_url): static
    {
        $this->poster_url = $poster_url;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): static
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return Collection<int, Reviews>
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Reviews $review): static
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews->add($review);
            $review->setShoww($this);
        }

        return $this;
    }

    public function removeReview(Reviews $review): static
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getShoww() === $this) {
                $review->setShoww(null);
            }
        }

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): static
    {
        $this->location = $location;

        return $this;
    }

    /**
     * @return Collection<int, Representation>
     */
    public function getRepresentations(): Collection
    {
        return $this->representations;
    }

    public function addRepresentation(Representation $representation): static
    {
        if (!$this->representations->contains($representation)) {
            $this->representations->add($representation);
            $representation->setTheShow($this);
        }

        return $this;
    }

    public function removeRepresentation(Representation $representation): static
    {
        if ($this->representations->removeElement($representation)) {
            // set the owning side to null (unless already changed)
            if ($representation->getTheShow() === $this) {
                $representation->setTheShow(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ArtistType>
     */
    public function getTroupe(): Collection
    {
        return $this->troupe;
    }

    public function addTroupe(ArtistType $troupe): static
    {
        if (!$this->troupe->contains($troupe)) {
            $this->troupe->add($troupe);
        }

        return $this;
    }

    public function removeTroupe(ArtistType $troupe): static
    {
        $this->troupe->removeElement($troupe);

        return $this;
    }
}

src/Controller/ShowController.php
<?php

namespace App\Controller;

use App\Entity\Showw;
use App\Entity\Reviews;
use App\Form\ReviewsType;
use App\Entity\Reservation;
use App\Repository\ShowwRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\AccessDeniedException;

class ShowController extends AbstractController
{
    private $security;
    private $entityManager;

    public function __construct(Security $security, EntityManagerInterface $entityManager)
    {
        $this->security = $security;
        $this->entityManager = $entityManager;
    }

    #[Route('/', name: 'show_index')]
    public function index(ShowwRepository $showwRepository): Response
    {
        return $this->render('show/index.html.twig', [
            'shows' => $showwRepository->findAll(),
        ]);
    }

    #[Route('/show/{id}/comments', name: 'show_comments')]
    public function showComments($id, EntityManagerInterface $entityManager): Response
    {
        $reviewRepository = $entityManager->getRepository(Reviews::class);
        $comments = $reviewRepository->findByShowWithUser($id);

        return $this->render('show/comments.html.twig', [
            'comments' => $comments,
        ]);
    }

    #[Route('/show/{id}', name: 'show_view')]
    public function viewShow($id, Request $request, EntityManagerInterface $entityManager, ValidatorInterface $validator): Response
    {
        $user = $this->getUser();
        $show = $entityManager->getRepository(Showw::class)->find($id);
        if (!$show) {
            throw $this->createNotFoundException('Spectacle non trouvé.');
        }

        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_REMEMBERED');

        if (!$this->hasPastReservation($show, $user)) {
            throw new AccessDeniedException('Vous devez avoir assisté à ce spectacle pour laisser un commentaire.');
        }

        $review = new Reviews();
        $form = $this->createForm(ReviewsType::class, $review);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $errors = $validator->validate($review);
            if (count($errors) > 0) {
                return $this->render('review/new.html.twig', [
                    'form' => $form->createView(),
                    'errors' => $errors,
                ]);
            } else {
                $entityManager->persist($review);
                $entityManager->flush();
            }
        }
        return $this->render('show/view.html.twig', [
            'show' => $show,
            'form' => $form->createView(),
        ]);
    }

    private function hasPastReservation(Showw $showw, UserInterface $user, EntityManagerInterface $entityManager): bool
    {
        $qb = $entityManager->createQueryBuilder();
    
        $query = $qb->select('r')
            ->from(Reservation::class, 'r')
            ->where('r.showw = :showw')
            ->andWhere('r.user = :user')
            ->andWhere('r.date < :now')
            ->setParameters([
                'showw' => $showw,
                'user' => $user,
                'now' => new \DateTime(),
            ])
            ->setMaxResults(1)
            ->getQuery();
    
        $result = $query->getResult();
    
        return !empty($result);
    }

    #[Route('/show/{slug}/comments', name: 'show_comments_by_slug')]
    public function showCommentsBySlug(string $slug, EntityManagerInterface $entityManager): Response
    {
        $show = $entityManager->getRepository(Showw::class)->findOneBy(['slug' => $slug]);
        
        if (!$show) {
            throw $this->createNotFoundException('Le spectacle demandé n\'existe pas.');
        }
        
        $comments = $entityManager->getRepository(Reviews::class)->findBy(['showw' => $show, 'validated' => true], ['id' => 'DESC']);
        
        return $this->render('show/comments_by_slug.html.twig', [
            'show' => $show,
            'comments' => $comments,
        ]);
    }
}

templates/show/comments.html.twig
{# templates/show/comments.html.twig #}

{% for comment in comments %}
    <div class="comment">
        <p>{{ comment.user.firstName }} {{ comment.user.lastName }} ({{ comment.stars }} étoiles)</p>
        <p>{{ comment.review }}</p>
        {% if is_granted('ROLE_ADMIN') and not comment.validated %}
            <form action="{{ path('comment_validate', {'id': comment.id}) }}" method="post">
                <button type="submit">Valider le commentaire</button>
            </form>
        {% endif %}
    </div>
{% endfor %}

templates/show/comments_by_slug.html.twig
{# templates/show/comments_by_slug.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}Commentaires pour {{ show.title }}{% endblock %}

{% block body %}
<h1>Commentaires pour {{ show.title }}</h1>

{% for comment in comments %}
    <div class="comment">
        <p><strong>{{ comment.user.firstName }} {{ comment.user.lastName }}</strong> ({{ comment.stars }} étoiles)</p>
        <p>{{ comment.review }}</p>
    </div>
{% else %}
    <p>Aucun commentaire pour ce spectacle.</p>
{% endfor %}

{% endblock %}

templates/show/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
<link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
{% endblock %}

{% block javascripts %}  
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
        $(function(){
            $('table#liste-shows').DataTable();
            
            //
            $('td.switchable').on('dblclick', function(event) {
                let $td = $(this);
                let idShow = $(this).attr('data-ref');
                let bookable = $(this).text();
                //console.log(idShow);
                const API_URL = 'http://localhost/reservationsSymfony/public/index.php/';
                
                $.ajax({
                    method: "POST",
                    url: API_URL+'show/switchBookable/'+idShow,
                    data: { idShow: idShow, bookable: bookable }
                }).done(function( msg ) {
                    if(bookable=='No') {
                        $td.text('Yes');
                    } else {
                        $td.text('No');
                    }
                }).fail(function(){
                    console.log('Erreur API');
                });
            });
            
        });
    </script>
{% endblock %}

{% block title %}Liste des spectacles{% endblock %}

{% block body %}
    <h1>Liste des spectacles</h1>

    <table id="liste-shows" class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Slug</th>
                <th>Title</th>
                <th>Poster_url</th>
                <th>Bookable</th>
                <th>Price</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for show in shows %}
            <tr>
                <td>{{ show.id }}</td>
                <td>{{ show.slug }}</td>
                <td>{{ show.title }}</td>
                <td>{{ show.posterUrl }}</td>
                <td class="switchable" data-ref="{{ show.id }}">{{ show.bookable ? 'Yes' : 'No' }}</td>
                <td>{{ show.price }}</td>
                <td>
                    <a href="{{ path('show_show', {'id': show.id}) }}">show</a>
                {% if is_granted('ROLE_ADMIN') %}
                    <a href="{{ path('show_edit', {'id': show.id}) }}">edit</a>
                    {{ include('show/_delete_form.html.twig') }}
                {% endif %}    
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% if is_granted('ROLE_ADMIN') %}
    <a href="{{ path('show_new') }}">Create new</a>
{% endif %}    
{% endblock %}

templates/show/view.html.twig
{# templates/show/view.html.twig #}

{% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
    {{ form_start(form) }}
        {{ form_row(form.review) }}
        {{ form_row(form.stars) }}
        <button type="submit">Publier le commentaire</button>
    {{ form_end(form) }}
{% endif %}